### ISSUE TITLE
Link is nick

### ISSUE THREAD

**Issue by Flapchik** [StyledStrike/gmod-custom-chat#12]
![image](https://user-images.githubusercontent.com/58729268/188283931-068ab1b9-c1dd-4568-89d6-27b647e12483.png)
![image](https://user-images.githubusercontent.com/58729268/188283950-96e968e8-6338-4cea-8d33-3e1da78fb4f3.png)
Any mention of the player leads to the insertion of a link

**Comment by shockpast** [comment]
@Flapchik change title to "Nick is Link" instead of "Link is Nick", because it doesn't make any sense.

**Comment by StyledStrike** [comment]
I might need to check if a string contains a player name (which is not ideal, but works as an temporary fix)
