### ISSUE TITLE
audio player is not working anymore

### ISSUE THREAD

**Issue by kaaskiller** [StyledStrike/gmod-custom-chat#13]
The url is working i tried also other links. It keeps showing 0 seconds and unable to click play.
The audio player did still work in commit 2ad7922 for me that i was still using. I guess it did break in commit 88157ab when you did change it. Not sure.
![image](https://github.com/StyledStrike/gmod-custom-chat/assets/25620150/0bb10424-9b9f-44e9-8247-68c16b504545)

**Comment by StyledStrike** [comment]
Turns out I had forgotten to set the `url` attribute for the audio player... Should be fixed now.
Also caught another bug while fixing this one, where the audio player would be removed as soon as another message came up
