### ISSUE TITLE
"SChatBox" vgui widget isn't fully instanced / standalone

### ISSUE THREAD

**Issue by EntranceJew** [StyledStrike/gmod-custom-chat#14]
the contents of `cl_chatbox` still lean heavily on on the SChat global, it requires the SChat to do things with it involving setting input-readiness and visibility.

although it wasn't designed for it, it'd be really handy to be able to utilize the renderer in isolation.
for example, i was trying to position it above people's heads like speech bubbles so that the messages someone posts would also be visible in a separate render over someone's head.

**Comment by StyledStrike** [comment]
The recent refactor renamed `SChatBox` to `CustomChatHistory`, and it now it can be created on its own, though of course it still relies on some functions from the `CustomChat` global for text formatting.

<details><summary>A little advice about your use case...</summary>
<p>
I'd like to remind you that CustomChatHistory is based on DHTML, and as such creating them is akin to opening tabs on a web browser. Keeping only a few instances for nearby players and removing them after those players get far away from yourself should mitigate the amount of memory that they use.
</p>
</details>
