### ISSUE TITLE
[bug?] opening chat and then quickly typing deletes first character

### ISSUE THREAD

**Issue by BamsTheSergal** [StyledStrike/gmod-custom-chat#2]
as the title says, this issue happens quite often when i am using this addon and trying to type quickly, it deletes the first character i typed.

**Comment by StyledStrike** [comment]
Apparently it takes a few frames to clear the text entry when opening the chat... I'm changing it to clear only when closing, and also dealing with another issue that might arise from doing that.

**Comment by StyledStrike** [comment]
Alright, that should do it. If the issue still persists, please lemme know here 👍🏼
