### ISSUE TITLE
Allow scripted tags

### ISSUE THREAD

**Issue by vugi99** [StyledStrike/gmod-custom-chat#26]
For example ranks depending on players, allow scripts to return the correct tag depending on the player when a message is received in OnPlayerChat.

CustomChat.SetCustomTagFunction(func)

func would return a string and a color which can be used to show the rank (or no rank if nil is returned)

**Comment by StyledStrike** [comment]
I've chosen to use a hook for this. Runs client side, and here's a example that was just added to the _README_:

```lua
hook.Add( "OverrideCustomChatTags", "custom_tags_example", function( ply )
    -- A sequential table with strings, colors or anything really
    local parts = {
        color_black, "(", Color( 0, 0, 255 ), "The " .. team.GetName( ply:Team() ), color_black, ") "
    }

    -- Should we keep the original custom tags that
    -- were added on the "[Admin] Chat Tags" menu?
    local keepOriginalParts = true

    return parts, keepOriginalParts
end )
```

**Comment by vugi99** [comment]
@StyledStrike Can you add an option to put the tag after the avatar icon ?
