### ISSUE TITLE
Leaving Custom Chat requires to press Enter.

### ISSUE THREAD

**Issue by shockpast** [StyledStrike/gmod-custom-chat#4]
You can't close Custom Chat without opening Main Menu when pressing ESC, only if you pressing Enter and sending something that you didn't want to send, that's not kinda good, if it's possible to do this, it will be nice, because it's more familiar way to close something by pressing ESC, not Enter.

**Comment by StyledStrike** [comment]
That was intentional. I think someone asked for that to be the case, but since I can't find the comment I'll just go ahead and reverse it.
