### ISSUE TITLE
Translations for phrases in menus.

### ISSUE THREAD

**Issue by shockpast** [StyledStrike/gmod-custom-chat#7]
Is there some plans for adding translations?

**Comment by StyledStrike** [comment]
Like some other of my addons, yes, I do have plans to add translations. _Soon™_

**Comment by StyledStrike** [comment]
Guess it wasn't that *Soon™* after all... Sorry about that
However we might be getting it at some point, I'm planning on refactoring the whole addon and this will be part of it.
