### ISSUE TITLE
There is no gap between DEAD and the player's nickname.

### ISSUE THREAD

**Issue by shockpast** [StyledStrike/gmod-custom-chat#8]
Title says it all.
![изображение](https://user-images.githubusercontent.com/81193284/177008354-79fd640f-2d84-4b66-b4bf-910858ccf507.png)

**Comment by StyledStrike** [comment]
Hmm, for some reason _italic_ text seems to ignore spaces around it

**Comment by StyledStrike** [comment]
Turns out it was a very small oversight
